import Link from "next/link";
import {notFound} from "next/navigation";
import {Breadcrumb} from "@/components/layout";
const pages:Record<string,{title:string;intro:string;sections:{heading:string;body:string}[]}> = {
  shipping:{title:"Shipping & returns",intro:"A little care, from our maison to your door. These are sample policies for the demo boutique.",sections:[{heading:"Choose your delivery",body:"Standard delivery is $10, or free when your total after discounts reaches $50. Express delivery is $18. Gift concierge delivery, including gift wrap and samples, is $14."},{heading:"Sample delivery times",body:"Standard: 3?5 days. Express: 1?2 days. These are illustrative times only; demo orders are never dispatched."},{heading:"Returns",body:"The sample return window is 7 days for unopened fragrances. To explore the support flow, use the contact form. No real purchases or returns are processed."}]},
  privacy:{title:"Your privacy",intro:"This storefront is a browser-based demonstration.",sections:[{heading:"What is saved",body:"Your bag, favorites, demo orders, reviews, profile, preferences and contact messages are stored locally in this browser. No account registration is required."},{heading:"Demo payments",body:"Checkout uses a sample card or simulated PayPal approval. It does not collect real card numbers or charge you. Use sample personal details when trying the demo."},{heading:"Your controls",body:"Reset shopping data from Account ? Settings ? Reset demo data, or clear this website?s browser storage. Product photos and fonts are loaded from external image and font services."}]},
  terms:{title:"Demo terms",intro:"Explore ABOOSTO as an interactive fragrance boutique.",sections:[{heading:"A demonstration storefront",body:"Products, prices, availability, reviews, delivery estimates and policies are sample content. Submitting a demo order does not create a real purchase."},{heading:"Payments and messages",body:"No payment is charged and no order, subscription or contact email is sent. All confirmations describe simulated actions saved in your browser."},{heading:"Saved data",body:"Demo data remains on this browser until you reset it or clear site storage. It is not synchronized between devices and is not a secure account service."}]}
};
export function generateStaticParams(){return Object.keys(pages).map(info=>({info}));}
export default async function InformationPage({params}:{params:Promise<{info:string}>}) {
  const {info}=await params;const page=pages[info];if(!page)notFound();
  return <div className="max-w-[850px] mx-auto px-5 py-10 pb-20"><Breadcrumb items={[{label:"Home",href:"/"},{label:page.title}]}/><h1 className="font-serif text-4xl mt-7">{page.title}</h1><p className="mt-4 text-[#8a767e] leading-7">{page.intro}</p><div className="bg-white luxury-card rounded-2xl p-6 sm:p-9 space-y-7 mt-8">{page.sections.map(section=><section key={section.heading}><h2 className="font-serif text-2xl text-[#520a22]">{section.heading}</h2><p className="text-sm leading-7 text-[#8a767e] mt-3">{section.body}</p></section>)}</div><div className="flex gap-5 mt-7 text-sm text-[#520a22] underline"><Link href="/contact">Contact the boutique</Link><Link href="/shop">Explore fragrances</Link><Link href="/account">My account</Link></div></div>;
}
