export type StaticProduct = {
  slug: string;
  name: string;
  brand: string;
  tagline: string;
  description: string;
  category: string;
  scentType: string;
  gender: string;
  price: number;
  compareAt?: number;
  rating: number;
  reviewCount: number;
  image: string;
  gallery: string[];
  sizes: string[];
  stock: number;
  badge?: string;
  isBestSeller?: boolean;
  isNewArrival?: boolean;
  isFeatured?: boolean;
  notesTop: string;
  notesHeart: string;
  notesBase: string;
  ingredients: string;
  howToUse: string;
};

export const IMG = {
  blushA: "https://images.pexels.com/photos/9957552/pexels-photo-9957552.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  blushB: "https://images.pexels.com/photos/9957568/pexels-photo-9957568.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  missDior: "https://images.pexels.com/photos/32630385/pexels-photo-32630385.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  goldTop: "https://images.pexels.com/photos/1961788/pexels-photo-1961788.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  givenchy: "https://images.pexels.com/photos/32630378/pexels-photo-32630378.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  crystal: "https://images.pexels.com/photos/36910560/pexels-photo-36910560.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  vintage: "https://images.pexels.com/photos/10536602/pexels-photo-10536602.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  flora: "https://images.pexels.com/photos/9957555/pexels-photo-9957555.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  peony: "https://images.pexels.com/photos/965730/pexels-photo-965730.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  pinkGold: "https://images.pexels.com/photos/9957575/pexels-photo-9957575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  bentley: "https://images.pexels.com/photos/7270666/pexels-photo-7270666.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  bentleySilver: "https://images.pexels.com/photos/7270664/pexels-photo-7270664.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  wool: "https://images.pexels.com/photos/30263576/pexels-photo-30263576.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  wildBlack: "https://images.pexels.com/photos/36834269/pexels-photo-36834269.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  noirStone: "https://images.pexels.com/photos/36834014/pexels-photo-36834014.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  moody: "https://images.pexels.com/photos/36779952/pexels-photo-36779952.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  cologne: "https://images.pexels.com/photos/7270663/pexels-photo-7270663.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  darkGold: "https://images.pexels.com/photos/11711826/pexels-photo-11711826.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  duoWood: "https://images.pexels.com/photos/11711832/pexels-photo-11711832.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  duoWhite: "https://images.pexels.com/photos/11711830/pexels-photo-11711830.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  amber: "https://images.pexels.com/photos/11216292/pexels-photo-11216292.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  whiteSolo: "https://images.pexels.com/photos/11711821/pexels-photo-11711821.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  blackGold: "https://images.pexels.com/photos/11711835/pexels-photo-11711835.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  mist: "https://images.pexels.com/photos/29395415/pexels-photo-29395415.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  joop: "https://images.pexels.com/photos/32630382/pexels-photo-32630382.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
  heroWoman: "https://images.pexels.com/photos/3774940/pexels-photo-3774940.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  elegantWoman: "https://images.pexels.com/photos/8217790/pexels-photo-8217790.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  sprayClose: "https://images.pexels.com/photos/12428350/pexels-photo-12428350.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  giftRoses: "https://images.pexels.com/photos/30399680/pexels-photo-30399680.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  flatlay: "https://images.pexels.com/photos/5492767/pexels-photo-5492767.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  flatlay2: "https://images.pexels.com/photos/5492852/pexels-photo-5492852.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
};

export const PRODUCTS: StaticProduct[] = [
  {
    slug: "chanel-chance-eau-tendre",
    name: "Chanel Chance Eau Tendre",
    brand: "Chanel",
    tagline: "A floral and fresh embrace with vibrant jasmine and white musk.",
    description: "Chanel Chance Eau Tendre is a timeless fragrance that captures the spirit of a confident, modern woman. Its delicate yet bold scent is perfect for any occasion, leaving a lasting impression wherever you go. Sparkling grapefruit-quince meets a heart of jasmine, finishing in a veil of white musk and cedar.",
    category: "Women",
    scentType: "Floral",
    gender: "Women",
    price: 120,
    compareAt: 148,
    rating: 4.8,
    reviewCount: 320,
    image: IMG.peony,
    gallery: [IMG.peony, IMG.blushA, IMG.pinkGold, IMG.flora],
    sizes: ["30 ml", "50 ml", "100 ml"],
    stock: 42,
    badge: "Best Seller",
    isBestSeller: true,
    isFeatured: true,
    notesTop: "Pink Pepper, Lemon, Grapefruit",
    notesHeart: "Jasmine, Iris, Hyacinth",
    notesBase: "White Musk, Patchouli, Cedar",
    ingredients: "Alcohol Denat., Parfum, Aqua, Citronellol, Geraniol, Linalool, Alpha-Isomethyl Ionone.",
    howToUse: "Spray on pulse points — wrists, neck and behind ears. Reapply after 6 hours. Layer with unscented lotion for longer wear.",
  },
  {
    slug: "ysl-libre-edp",
    name: "YSL Libre Eau de Parfum",
    brand: "YSL",
    tagline: "Bold lavender and orange blossom — freedom in a bottle.",
    description: "YSL Libre is a statement of absolute freedom. Fiery lavender from France collides with sensual Moroccan orange blossom and daring musk accord. For the woman who lives by her own rules, Libre burns bright from desk to dinner.",
    category: "Women",
    scentType: "Oriental",
    gender: "Women",
    price: 135,
    rating: 4.9,
    reviewCount: 284,
    image: IMG.amber,
    gallery: [IMG.amber, IMG.darkGold, IMG.blackGold, IMG.blushB],
    sizes: ["30 ml", "50 ml", "90 ml"],
    stock: 36,
    badge: "Iconic",
    isBestSeller: true,
    isFeatured: true,
    notesTop: "Lavender, Mandarin, Blackcurrant",
    notesHeart: "Orange Blossom, Jasmine Sambac",
    notesBase: "Vanilla Bourbon, Musk, Ambergris",
    ingredients: "Alcohol, Parfum, Benzyl Salicylate, Linalool, Limonene, Coumarin, Geraniol.",
    howToUse: "Mist generously on neck and hair. Libre projects beautifully — 2 to 3 sprays is enough for all-day presence.",
  },
  {
    slug: "dior-sauvage-edt",
    name: "Dior Sauvage Eau de Toilette",
    brand: "Dior",
    tagline: "Radically fresh, raw and noble — the modern masculine icon.",
    description: "Dior Sauvage is a radically fresh composition inspired by wide-open spaces and rocky landscapes under a blue sky. Calabrian bergamot bursts over Sichuan pepper and ambroxan, creating a trail that is both powerful and refined.",
    category: "Men",
    scentType: "Fresh",
    gender: "Men",
    price: 125,
    rating: 4.8,
    reviewCount: 512,
    image: IMG.noirStone,
    gallery: [IMG.noirStone, IMG.wildBlack, IMG.moody, IMG.cologne],
    sizes: ["60 ml", "100 ml", "200 ml"],
    stock: 58,
    badge: "Best Seller",
    isBestSeller: true,
    isFeatured: true,
    notesTop: "Calabrian Bergamot, Pepper",
    notesHeart: "Sichuan Pepper, Lavender, Geranium",
    notesBase: "Ambroxan, Cedar, Labdanum",
    ingredients: "Alcohol, Parfum, Aqua, Limonene, Linalool, Citral, Coumarin.",
    howToUse: "Apply 2 sprays to neck and chest. Ideal for day and night — magnetic in every season.",
  },
  {
    slug: "lancome-la-vie-est-belle",
    name: "Lancôme La Vie Est Belle",
    brand: "Lancôme",
    tagline: "Joyful iris and praline — happiness made visible.",
    description: "La Vie Est Belle is a universal declaration of happiness. Elegant iris pallida floats over jasmine and orange blossom, melting into a gourmand heart of praline and warm vanilla. The scent of a life beautifully lived.",
    category: "Women",
    scentType: "Fruity",
    gender: "Women",
    price: 110,
    compareAt: 132,
    rating: 4.7,
    reviewCount: 198,
    image: IMG.blushA,
    gallery: [IMG.blushA, IMG.pinkGold, IMG.flora, IMG.crystal],
    sizes: ["30 ml", "50 ml", "100 ml"],
    stock: 51,
    badge: "Loved",
    isBestSeller: true,
    notesTop: "Blackcurrant, Pear",
    notesHeart: "Iris, Jasmine, Orange Blossom",
    notesBase: "Praline, Vanilla, Patchouli",
    ingredients: "Alcohol Denat., Parfum, Aqua, Benzyl Salicylate, Linalool, Coumarin.",
    howToUse: "Spray in a cloud and walk through for an even, luminous veil of scent.",
  },
  {
    slug: "miss-dior-blooming-bouquet",
    name: "Miss Dior Blooming Bouquet",
    brand: "Dior",
    tagline: "A tender bouquet of peony and Damascus rose.",
    description: "Miss Dior Blooming Bouquet is crafted like a dress embroidered with a thousand flowers. Fresh Calabrian bergamot opens into a heart of peony and Damascus rose, resting on a base of white musk. Tender, fresh, utterly romantic.",
    category: "Women",
    scentType: "Floral",
    gender: "Women",
    price: 130,
    rating: 4.8,
    reviewCount: 176,
    image: IMG.missDior,
    gallery: [IMG.missDior, IMG.peony, IMG.blushB, IMG.flora],
    sizes: ["30 ml", "50 ml", "100 ml"],
    stock: 44,
    badge: "New Arrival",
    isNewArrival: true,
    isFeatured: true,
    notesTop: "Sicilian Bergamot, Sweet Pea",
    notesHeart: "Peony, Damascus Rose, Apricot",
    notesBase: "White Musk, Peach",
    ingredients: "Alcohol, Parfum, Aqua, Citronellol, Geraniol, Hexyl Cinnamal.",
    howToUse: "Dab on collarbones and wrists. Perfect for spring days, weddings and golden evenings.",
  },
  {
    slug: "armani-si-intense",
    name: "Giorgio Armani Sì Intense",
    brand: "Armani",
    tagline: "Blackcurrant nectar over velvety rose and patchouli.",
    description: "Sì Intense is magnetic and sophisticated. Blackcurrant nectar and Turkish rose absolute melt into a deep base of patchouli and vanilla Bourbon. A fragrance for saying sì to passion, freedom and love.",
    category: "Women",
    scentType: "Oriental",
    gender: "Women",
    price: 115,
    rating: 4.7,
    reviewCount: 142,
    image: IMG.blackGold,
    gallery: [IMG.blackGold, IMG.darkGold, IMG.amber, IMG.mist],
    sizes: ["30 ml", "50 ml", "100 ml"],
    stock: 39,
    isNewArrival: true,
    notesTop: "Blackcurrant Nectar, Mandarin",
    notesHeart: "Turkish Rose, Davana, Neroli",
    notesBase: "Patchouli, Vanilla Bourbon",
    ingredients: "Alcohol, Parfum, Aqua, Limonene, Linalool, Citronellol, Eugenol.",
    howToUse: "One spray on each wrist and one on the neck — Sì Intense lingers for 8+ hours.",
  },
  {
    slug: "tom-ford-black-orchid",
    name: "Tom Ford Black Orchid",
    brand: "Tom Ford",
    tagline: "Dark, decadent and unforgettable — pure seduction.",
    description: "Black Orchid is Tom Ford's legendary introduction to the world of fragrance. Black truffle and ylang melt into black orchid, dark chocolate and incense. Luxurious, sensual and utterly distinctive.",
    category: "Unisex",
    scentType: "Oriental",
    gender: "Unisex",
    price: 140,
    rating: 4.9,
    reviewCount: 267,
    image: IMG.wildBlack,
    gallery: [IMG.wildBlack, IMG.noirStone, IMG.moody, IMG.wool],
    sizes: ["30 ml", "50 ml", "100 ml"],
    stock: 28,
    badge: "Cult Classic",
    isBestSeller: true,
    notesTop: "Black Truffle, Ylang-Ylang, Bergamot",
    notesHeart: "Black Orchid, Lotus, Dark Chocolate",
    notesBase: "Incense, Patchouli, Amber, Vanilla",
    ingredients: "Alcohol Denat., Parfum, Aqua, Cinnamal, Eugenol, Linalool.",
    howToUse: "Evening wear essential. Spray lightly — Black Orchid is potent and long-lasting.",
  },
  {
    slug: "baccarat-rouge-540",
    name: "Maison Baccarat Rouge 540",
    brand: "Maison",
    tagline: "Saffron, amberwood and fir — luminous crystal fire.",
    description: "Baccarat Rouge 540 is the scent of the moment — airy yet dense, radiant yet intimate. Saffron and jasmine glow over amberwood and fir resin, leaving a trail that turns every head in the room.",
    category: "Unisex",
    scentType: "Woody",
    gender: "Unisex",
    price: 220,
    rating: 4.9,
    reviewCount: 341,
    image: IMG.whiteSolo,
    gallery: [IMG.whiteSolo, IMG.duoWhite, IMG.mist, IMG.amber],
    sizes: ["40 ml", "70 ml"],
    stock: 22,
    badge: "Limited",
    isNewArrival: true,
    isFeatured: true,
    notesTop: "Saffron, Jasmine",
    notesHeart: "Amberwood, Ambergris",
    notesBase: "Fir Resin, Cedar, Musk",
    ingredients: "Alcohol, Parfum, Aqua, Benzyl Benzoate, Citronellol, Linalool.",
    howToUse: "A collector's scent. 1–2 sprays on skin; the aura develops over hours.",
  },
  {
    slug: "versace-bright-crystal",
    name: "Versace Bright Crystal",
    brand: "Versace",
    tagline: "Crystalline peony and magnolia — pure Mediterranean light.",
    description: "Bright Crystal is fresh, sensual and luminous. Iced accord, yuzu and pomegranate open into peony, magnolia and lotus, grounded in mahogany and amber. Donatella's ode to feminine strength.",
    category: "Women",
    scentType: "Floral",
    gender: "Women",
    price: 95,
    compareAt: 120,
    rating: 4.6,
    reviewCount: 210,
    image: IMG.crystal,
    gallery: [IMG.crystal, IMG.blushB, IMG.missDior, IMG.peony],
    sizes: ["30 ml", "50 ml", "90 ml"],
    stock: 60,
    badge: "-20%",
    notesTop: "Yuzu, Pomegranate, Iced Accord",
    notesHeart: "Peony, Magnolia, Lotus",
    notesBase: "Mahogany, Amber, Musk",
    ingredients: "Alcohol Denat., Parfum, Aqua, Limonene, Linalool, Citral.",
    howToUse: "Everyday signature scent. Refresh at midday for a burst of radiance.",
  },
  {
    slug: "gucci-bloom-ambrosia",
    name: "Gucci Bloom Ambrosia",
    brand: "Gucci",
    tagline: "Jasmine bud and tuberose under moonlit honeysuckle.",
    description: "Gucci Bloom Ambrosia di Fiori is a nocturnal chapter of the Bloom story. Jasmine bud, tuberose and Rangoon creeper deepen into honeysuckle and velvety orris. Rich, romantic and intoxicating.",
    category: "Women",
    scentType: "Floral",
    gender: "Women",
    price: 105,
    compareAt: 140,
    rating: 4.6,
    reviewCount: 158,
    image: IMG.flora,
    gallery: [IMG.flora, IMG.blushA, IMG.peony, IMG.pinkGold],
    sizes: ["30 ml", "50 ml", "100 ml"],
    stock: 47,
    badge: "-25%",
    notesTop: "Jasmine Bud, Honeysuckle",
    notesHeart: "Tuberose, Rangoon Creeper",
    notesBase: "Orris, Musk",
    ingredients: "Alcohol, Parfum, Aqua, Benzyl Alcohol, Hydroxycitronellal.",
    howToUse: "Spray on décolletage for evening. Blooms beautifully in warm air.",
  },
  {
    slug: "jo-malone-english-pear",
    name: "Jo Malone English Pear & Freesia",
    brand: "Jo Malone",
    tagline: "Orchard freshness wrapped in soft white freesia.",
    description: "English Pear & Freesia captures the essence of autumn in an English orchard. Ripe King William pear, white freesia and wild rose settle into patchouli and amber. Fresh, elegant and endlessly layerable.",
    category: "Unisex",
    scentType: "Fruity",
    gender: "Unisex",
    price: 102,
    compareAt: 135,
    rating: 4.7,
    reviewCount: 189,
    image: IMG.duoWhite,
    gallery: [IMG.duoWhite, IMG.whiteSolo, IMG.amber, IMG.givenchy],
    sizes: ["30 ml", "50 ml", "100 ml"],
    stock: 53,
    badge: "-24%",
    notesTop: "King William Pear",
    notesHeart: "White Freesia, Wild Rose",
    notesBase: "Patchouli, Amber, Musk",
    ingredients: "Alcohol Denat., Parfum, Aqua, Geraniol, Citronellol, Limonene.",
    howToUse: "Layer with Wood Sage & Sea Salt for a bespoke ABOOSTO ritual.",
  },
  {
    slug: "creed-aventus",
    name: "Creed Aventus",
    brand: "Creed",
    tagline: "Pineapple smoke and birch — the scent of success.",
    description: "Creed Aventus is the definitive masculine luxury fragrance. Pineapple, blackcurrant and apple ignite over birch, jasmine and patchouli, drying down to vanilla, musk and oakmoss. Worn by leaders and legends.",
    category: "Men",
    scentType: "Woody",
    gender: "Men",
    price: 310,
    rating: 4.9,
    reviewCount: 402,
    image: IMG.cologne,
    gallery: [IMG.cologne, IMG.bentley, IMG.bentleySilver, IMG.moody],
    sizes: ["50 ml", "100 ml"],
    stock: 18,
    badge: "Prestige",
    isFeatured: true,
    notesTop: "Pineapple, Blackcurrant, Apple, Bergamot",
    notesHeart: "Birch, Jasmine, Rose, Patchouli",
    notesBase: "Vanilla, Musk, Oakmoss, Ambergris",
    ingredients: "Alcohol, Parfum, Aqua, Limonene, Linalool, Citral.",
    howToUse: "Signature scent for milestones. Two sprays — power without shouting.",
  },
  {
    slug: "dior-jadore",
    name: "Dior J'adore Eau de Parfum",
    brand: "Dior",
    tagline: "A golden bouquet of ylang and Damascus rose.",
    description: "J'adore is a grand feminine floral — a bouquet composed to perfection. Ylang-ylang from the Comoros, Damascus rose and jasmine Sambac unfurl in golden light. The ultimate expression of femininity.",
    category: "Women",
    scentType: "Floral",
    gender: "Women",
    price: 138,
    rating: 4.7,
    reviewCount: 230,
    image: IMG.blushB,
    gallery: [IMG.blushB, IMG.missDior, IMG.peony, IMG.goldTop],
    sizes: ["30 ml", "50 ml", "100 ml"],
    stock: 40,
    isBestSeller: true,
    notesTop: "Ylang-Ylang, Bergamot, Pear",
    notesHeart: "Damascus Rose, Jasmine Sambac, Tuberose",
    notesBase: "Musk, Cedar, Blackberry",
    ingredients: "Alcohol, Parfum, Aqua, Benzyl Salicylate, Linalool, Geraniol.",
    howToUse: "The finishing touch — mist on neck and shoulders before stepping out.",
  },
  {
    slug: "ysl-black-opium",
    name: "YSL Black Opium EDP",
    brand: "YSL",
    tagline: "Adrenaline coffee over vanilla and white flowers.",
    description: "Black Opium is rock-chic and glamorous. Black coffee and pink pepper spark over jasmine and orange blossom, sinking into vanilla, patchouli and cedar. Addictive, electric, unforgettable.",
    category: "Women",
    scentType: "Oriental",
    gender: "Women",
    price: 128,
    compareAt: 150,
    rating: 4.8,
    reviewCount: 295,
    image: IMG.bentley,
    gallery: [IMG.bentley, IMG.bentleySilver, IMG.blackGold, IMG.mist],
    sizes: ["30 ml", "50 ml", "90 ml"],
    stock: 45,
    badge: "-15%",
    isNewArrival: true,
    notesTop: "Black Coffee, Pink Pepper, Pear",
    notesHeart: "Jasmine, Orange Blossom, Almond",
    notesBase: "Vanilla, Patchouli, Cedar, Musk",
    ingredients: "Alcohol, Parfum, Aqua, Coumarin, Linalool, Limonene.",
    howToUse: "Night-out icon. Spray on pulse points and hair for maximum sillage.",
  },
  {
    slug: "chanel-coco-mademoiselle",
    name: "Chanel Coco Mademoiselle",
    brand: "Chanel",
    tagline: "Sparkling orange and bold rose over vetiver.",
    description: "Coco Mademoiselle is the essence of a free, daring woman. Sparkling Sicilian orange and Calabrian bergamot meet a transparent rose and jasmine heart, grounded in patchouli and vetiver. Irresistibly Parisian.",
    category: "Women",
    scentType: "Oriental",
    gender: "Women",
    price: 142,
    rating: 4.8,
    reviewCount: 318,
    image: IMG.goldTop,
    gallery: [IMG.goldTop, IMG.amber, IMG.darkGold, IMG.duoWood],
    sizes: ["35 ml", "50 ml", "100 ml"],
    stock: 33,
    badge: "Iconic",
    isBestSeller: true,
    notesTop: "Sicilian Orange, Bergamot, Mandarin",
    notesHeart: "Rose, Jasmine, Lychee",
    notesBase: "Patchouli, Vetiver, Vanilla, Musk",
    ingredients: "Alcohol, Parfum, Aqua, Citronellol, Geraniol, Limonene.",
    howToUse: "A timeless signature. Layer EDP with body lotion for all-day elegance.",
  },
  {
    slug: "aboosto-oud-royal-gift-set",
    name: "ABOOSTO Oud Royal Gift Set",
    brand: "ABOOSTO",
    tagline: "Our signature oud trilogy — Smoke, Rose & Amber.",
    description: "The ABOOSTO Oud Royal Gift Set is our love letter to Middle Eastern perfumery. Three 30ml treasures — Oud Smoke, Oud Rose and Oud Amber — presented in a blush gift coffret with gold detailing. For collectors and gift-givers who want only the extraordinary.",
    category: "Gift Sets",
    scentType: "Woody",
    gender: "Unisex",
    price: 189,
    compareAt: 240,
    rating: 4.9,
    reviewCount: 96,
    image: IMG.duoWood,
    gallery: [IMG.duoWood, IMG.giftRoses, IMG.flatlay, IMG.mist],
    sizes: ["3 × 30 ml", "3 × 50 ml"],
    stock: 26,
    badge: "Gift Pick",
    isNewArrival: true,
    isFeatured: true,
    notesTop: "Saffron, Cardamom, Bergamot",
    notesHeart: "Laotian Oud, Taif Rose, Incense",
    notesBase: "Amber, Sandalwood, Tonka, Musk",
    ingredients: "Alcohol, Parfum, Aqua — crafted in small batches with natural oud oils.",
    howToUse: "Discover your oud character: Smoke by night, Rose by day, Amber for occasions.",
  },
];

export const CATEGORIES = [
  { name: "Women", image: IMG.peony, count: 9 },
  { name: "Men", image: IMG.noirStone, count: 3 },
  { name: "Unisex", image: IMG.whiteSolo, count: 4 },
  { name: "Gift Sets", image: IMG.giftRoses, count: 2 },
  { name: "Signature", image: IMG.blushA, count: 6 },
  { name: "New In", image: IMG.missDior, count: 5 },
];

export const BRANDS = ["Chanel", "Dior", "YSL", "Lancôme", "Armani", "Tom Ford", "Versace", "Gucci", "Jo Malone", "Creed", "ABOOSTO", "Maison"];
export const SCENT_TYPES = ["Floral", "Woody", "Oriental", "Fresh", "Fruity"];

export const TESTIMONIALS = [
  { name: "Amira Hassan", location: "Mogadishu", rating: 5, text: "Amazing quality! The fragrance lasts all day. Highly recommend ABOOSTO — the packaging felt like opening a treasure.", product: "Chanel Chance" },
  { name: "Fatima Ali", location: "Hargeisa", rating: 5, text: "Beautiful packaging and fast delivery. I'm in love! My Sì Intense gets compliments everywhere I go.", product: "Armani Sì Intense" },
  { name: "Noura Mohamed", location: "Dubai", rating: 5, text: "The best place to buy original perfumes in Somalia. 100% authentic, sealed, and the gift wrapping is stunning.", product: "Baccarat Rouge 540" },
  { name: "Yasmin Said", location: "Nairobi", rating: 5, text: "Ordered the Oud Royal set for my mother — she cried. Elegant, long-lasting, and the gold coffret is keepsake-worthy.", product: "Oud Royal Gift Set" },
];

export const HERO_SLIDES = [
  {
    eyebrow: "The Autumn Atelier Edit",
    title: "A Fragrance For Every Occasion",
    subtitle: "Discover premium perfumes and signature scents crafted for elegance, confidence and everyday beauty.",
    image: IMG.peony,
  },
];

export function price(n: number) {
  return `$${n}`;
}
